<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <Authors>Hank McCord</Authors>
    <Description>A NuGet credential provider plugin that supplies the .NET CLI credentials from **Windows Credential Manager** for self-hosted Azure DevOps (TFS) servers.</Description>
    <PackageId>CredentialManager.CredentialProvider.NuGet.Tool</PackageId>
    <PackageProjectUrl>https://github.com/hymccord/CredentialManager.CredentialProvider</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>NuGet Credential Manager TFS</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <PackAsTool>true</PackAsTool>
    <RollForward>Major</RollForward>
    <ToolCommandName>nuget-plugin-credential-manager-credential-provider</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="" Visible="false" />
    <None Include="icon.png" Pack="true" PackagePath="" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Framework.Win32.CredentialManager" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
    <PackageReference Include="MinVer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NReco.Logging.File" />
    <PackageReference Include="NuGet.Protocol" />
  </ItemGroup>

  <Target Name="DefineMinVerPackageVersion" AfterTargets="MinVer" Condition="'$(MinVerBuildMetadata)' != ''">
    <PropertyGroup>
      <PackageVersion>$(PackageVersion)+$(MinVerBuildMetadata)</PackageVersion>
      <Version>$(PackageVersion)</Version>
    </PropertyGroup>
  </Target>

</Project>
